# Artificial Neural Network

### Importing the libraries

In [51]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [52]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [53]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
# RowNumber, CustomerId and Surname are not included in X
y = dataset.iloc[:, -1].values

In [54]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [55]:
print(X[0])

[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]


In [56]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [58]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
# Female --> 0 | Male --> 1

In [59]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [60]:
print(X[0])

[619 'France' 0 42 2 0.0 1 1 1 101348.88]


One Hot Encoding the "Geography" column

In [61]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
# France --> [1 0 0] | Germany --> [0 1 0] | Spain --> [0 0 1]

In [62]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [63]:
print(X[0])

[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


### Splitting the dataset into the Training set and Test set

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [66]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [67]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [68]:
print(X_train[0])

[-1.01460667 -0.5698444   1.74309049  0.16958176 -1.09168714 -0.46460796
  0.00666099 -1.21571749  0.8095029   0.64259497 -1.03227043  1.10643166]


## Part 2 - Building the ANN

### Initializing the ANN

In [69]:
ann = tf.keras.models.Sequential()
# An artificial neural network as a sequence of layers

### Adding the input layer and the first hidden layer

In [70]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# Rectifier activation function --> relu

### Adding the second hidden layer

In [71]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# The number of units has no rule of thumb

### Adding the output layer

In [72]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Sigmoid function to obtain values from 0 to 1 with a probability

## Part 3 - Training the ANN

### Compiling the ANN

In [73]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# Configures the model for training

### Training the ANN on the Training set

In [74]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)
# Trains the model with the training dataset

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5028 - accuracy: 0.7949
Epoch 2/100
250/250 [==============================] - 0s 989us/step - loss: 0.4575 - accuracy: 0.7974
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4417 - accuracy: 0.7972
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4343 - accuracy: 0.8021
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4300 - accuracy: 0.8079
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4269 - accuracy: 0.8114
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4236 - accuracy: 0.8159
Epoch 8/100
250/250 [==============================] - 0s 984us/step - loss: 0.4204 - accuracy: 0.8229
Epoch 9/100
250/250 [==============================] - 0s 994us/step - loss: 0.4176 - accuracy: 0.8256
Epoch 10/100
250/250 [==============================] - 0s 934us/step - loss: 0.4146 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [80]:
new_data = sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])
print(new_data)
new_prediction = ann.predict(new_data)
print(new_prediction)
print(new_prediction > 0.5)

[[ 0.98560362 -0.5698444  -0.57369368 -0.52111599  0.91601335  0.10961719
  -0.68538967 -0.2569057   0.8095029   0.64259497  0.9687384  -0.87203322]]
[[0.04413947]]
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [81]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [83]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

In [85]:
print(cm)
# 0 no false: 1512/1704 correct predictions (192 wrong)
# 1 yes true: 213/296 correct predictions (83 wrong)

[[1512   83]
 [ 192  213]]


In [86]:
print(accuracy)
# 86% total of correct predictions (14% wrong)

0.8625
